train_path : "/content/drive/MyDrive/datasets/tamilatis/train_intent.pkl"
valid_path : "/content/drive/MyDrive/datasets/tamilatis/val_intent.pkl"
test_path : "/content/drive/MyDrive/datasets/tamilatis/test_intent.pkl"
output_dir: "/saved_models"
num_labels: 78
num_intents: 23