batch_size: 32
weight_decay: 0.01
lr: 1e-4
max_epochs: 20
patience: 5
scheduler: "linear"
warmup_steps: 10
do_train: False
do_predict: True
ner_cls_path: /content/ner_cls.csv
intent_cls_path: /content/intent_cls.csv