batch_size: 32
weight_decay: 0.01
lr: 6e-3
max_epochs: 50
patience: 5
scheduler: "exponential"
warmup_steps: 10
random_seed: 1234
do_train: False
do_predict: True
ner_cls_path: /content/ner_ptuned_cls_64.csv
intent_cls_path: /content/intent_ptuned_cls_64.csv