batch_size: 32
weight_decay: 0.01
lr: 1e-4
max_epochs: 20
patience: 5
scheduler: "cosine"
warmup_steps: 0
do_train: True
do_predict: False
ner_cls_path: /content/ner_cls_rlw.csv
intent_cls_path: /content/intent_cls_rlw.csv